[build]
  publish = "public"
  command = "yarn prod"

[[redirects]]
  from = "/thumbnailer/*"
  to = "https://thumbnailer.netlify.com/:splat"
  status = 200

[[headers]]
  for = "/"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
