[build]
  publish = "public"
  command = "npm run prod"

[[redirects]]
  from = "/thumbnailer/*"
  to = "https://thumbnailer.netlify.com/:splat"
  status = 200

[[headers]]
  for = "/"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Link = [
      "</css/index.css>; rel=preload; as=stylesheet",
      "</js/main.js>; rel=preload; as=script"
    ]
